# Build stage
FROM node:20 AS build
WORKDIR /app
COPY ecommerce/frontend/package*.json ./
RUN npm install
COPY ecommerce/frontend/ ./
RUN npm run build

# Run stage
FROM nginx:alpine
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
