spring.application.name=ecommerce_project
spring.datasource.username=root
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_analytics
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8081
app.jwt.secret=20015YEpeqwe07y39eto999EPD0709v1208
app.jwt.expiration-ms=86400000
gemini.api.key="AIzaSyDlQqF6L4fKOEaOcROE1XtutQ3uVeGZHmg";